plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'
    - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
      spec: '@yarnpkg/plugin-version'

logFilters: # https://yarnpkg.com/configuration/yarnrc#logFilters
    - code: 'YN0062' # fsevents message, text based ignore wouldn't work
      level: 'discard'

yarnPath: .yarn/releases/yarn-berry.cjs
packageExtensions:
    # awaiting fix: https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/issues/147
    '@endemolshinegroup/cosmiconfig-typescript-loader@*':
        peerDependenciesMeta:
            typescript:
                optional: true
    'eslint-config-airbnb-typescript@*':
        dependencies:
            eslint: '*'
            eslint-plugin-import: '*'
            eslint-plugin-jsx-a11y: '*'
            eslint-plugin-react: '*'
            eslint-plugin-react-hooks: '*'
    '@storybook/core@*':
        dependencies:
            webpack: '*'
    'react-dev-utils@*':
        dependencies:
            typescript: '*'
            webpack: '*'
    # 'storybook-addon-performance@*':
    #   dependencies:
    #     react-is: '*'
    '@mdx-js/loader@*':
        dependencies:
            react: '*'
    # https://yarnpkg.com/features/pnp#different-behaviours-based-on-workspace--not-a-workspace
    'mercurius@*':
        peerDependencies:
            fastify: '*'
    'fastify-cookie@*':
        peerDependencies:
            fastify: '*'
    'pino@*':
        dependencies:
            pino-pretty: '*'
    'relay-compiler@11.0.2':
        peerDependencies:
            relay-compiler-language-typescript: 'v14.0.0'
            # relay-runtime: '11.0.2'
            '@types/react-relay': '*'
            '@types/relay-runtime': '*'
            'typescript': '*'
    'babel-plugin-relay@*':
        dependencies:
            '@babel/runtime': '*'
    # '@prisma/client@*':
    #     dependencies:
    #         '.prisma': 'link:See "resolution" field of package.json'
    # '@reach/router@1.3.4':
    #   dependencies:
    #     react: '*'
    # 'create-react-context@*':
    #   dependencies:
    #     react: '*'
